# Generated by Django 5.1 on 2024-09-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_bookmark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
