# Generated by Django 5.1 on 2024-09-20 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
